FROM dart:stable AS build
WORKDIR /app

COPY pubspec.yaml ./
RUN dart pub get

COPY . .

RUN dart pub get --offline
RUN dart compile exe bin/server.dart -o bin/server

FROM debian:bookworm-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=build /runtime/ /
COPY --from=build /app/bin/server /app/bin/server

ENV PORT=10000
EXPOSE 10000

CMD ["/app/bin/server"]
